import {createState,ITEMS,SKILLS,NPCS,getTopics,chooseTopic,chooseResponse,act,allocateAttribute,serialize,deserialize,getJournal,getEffects} from './systems.js';
const $=id=>document.getElementById(id),T=window.THREE;
let state=createState(),paused=true,crouched=false,yaw=0,pitch=.24,clock=0,last=0,nearest=null,activeNPC=null,dialogue=null,toastUntil=0,attackCooldown=0,veilUntil=0,heat=0,underground=false,roof=false,alarm=0,saveClock=0,focusReturn=null,pendingTakedown=null,pendingClimb=null,uiClock=0,coverGraceUntil=0,coverTime=0,wasInCover=false;
const keys={},stick={x:0,y:0},pos={x:0,z:22},colliders=[],lightSources=[],interactions=[],guards=[],npcs=[],gates=[{id:'bailey',name:'Inner Bailey',x:0,z:22},{id:'lowtown',name:'Lowtown',x:-18,z:16},{id:'forge',name:'Forge Quarter',x:20,z:16},{id:'garrison',name:'Garrison Row',x:19,z:0}];
const storageKey='castle-realm-a-quiet-passage-v1';
let storageAvailable=true;
try{const saved=localStorage.getItem(storageKey);if(saved)state=deserialize(saved);}catch{storageAvailable=false;}
function worldState(){state.world=state.world||{};state.world.playerPosition=state.world.playerPosition||{x:0,z:22};state.world.guards=state.world.guards||{};state.world.collected=state.world.collected||{};state.world.visited=state.world.visited||{bailey:true};state.world.underneath=!!state.world.underneath;return state.world;}
worldState();Object.assign(pos,state.world.playerPosition);underground=state.world.underneath;
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(text){if(!text)return;$('toast').textContent=text;$('toast').classList.add('show');toastUntil=uiClock+4.5;}
function save(announce=false){
  const w=worldState();
  // An interrupted climb returns to the last stable footing, without practice.
  w.playerPosition={...(pendingClimb?pendingClimb.from:pos)};
  Object.assign(w,{underneath:underground,roof:pendingClimb?pendingClimb.fromRoof:roof,crouched,yaw,pitch,alarm,heat,veilRemaining:Math.min(6,Math.max(0,veilUntil-clock)),attackRemaining:Math.max(0,attackCooldown-clock)});
  for(const g of guards)w.guards[g.id]={status:g.status,health:g.health,x:g.x,z:g.z,to:g.to,heading:g.heading,suspicion:g.suspicion,alerted:!!g.alerted,graceUsed:!!g.graceUsed,graceRemaining:g.graceRemaining||0,lastX:g.lastX??g.x,lastZ:g.lastZ??g.z,attackRemaining:Math.max(0,g.attackAt-clock)};
  try{localStorage.setItem(storageKey,serialize(state));if(announce)toast('Progress saved on this device.');}catch{storageAvailable=false;if(announce)toast('Device storage unavailable. Use Export save in the menu.');}
}
function perform(action,context){const r=act(state,action,context);toast(r?.message);save();return r;}
const scene=new T.Scene();scene.background=new T.Color('#64717e');scene.fog=new T.Fog('#64717e',36,100);
let renderer;try{renderer=new T.WebGLRenderer({canvas:$('scene'),antialias:true,powerPreference:'high-performance'});}catch(e){$('shade').hidden=false;$('panelTitle').textContent='3D graphics unavailable';$('panelBody').textContent='Open this file in a browser with WebGL enabled.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputEncoding=T.sRGBEncoding;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const camera=new T.PerspectiveCamera(60,innerWidth/innerHeight,.08,160),surface=new T.Group(),below=new T.Group();scene.add(surface,below);
scene.add(new T.HemisphereLight('#ccd8e8','#3c3529',.8));const sun=new T.DirectionalLight('#ffe0ab',1.9);sun.position.set(-25,48,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-44,right:44,top:44,bottom:-44,near:1,far:120});sun.shadow.bias=-.0005;scene.add(sun);
function mat(c,extra={}){return new T.MeshStandardMaterial({color:c,roughness:.9,...extra});}
const stone=mat('#77786e'),dark=mat('#424d53'),wood=mat('#665445'),roofMat=mat('#475960'),gold=mat('#b79452'),earth=mat('#66705b'),pale=mat('#bab2a0'),brick=mat('#958b77');
function box(x,y,z,w,h,d,m=stone,group=surface,solid=false){const a=new T.Mesh(new T.BoxGeometry(w,h,d),m);a.position.set(x,y+h/2,z);a.castShadow=true;a.receiveShadow=true;group.add(a);if(solid)colliders.push({x,z,w,d,below:group===below});return a;}
function cyl(x,y,z,r,h,m=stone,group=surface,segments=12){const a=new T.Mesh(new T.CylinderGeometry(r,r,h,segments),m);a.position.set(x,y+h/2,z);a.castShadow=true;a.receiveShadow=true;group.add(a);return a;}
function torch(x,z,y=2,group=surface){lightSources.push({x,z,under:group===below});box(x,y-.8,z,.15,.9,.18,wood,group);const flame=new T.Mesh(new T.OctahedronGeometry(.19),mat('#ffd090',{emissive:'#ff9e40',emissiveIntensity:2}));flame.position.set(x,y+.15,z);group.add(flame);const l=new T.PointLight('#ffa852',1.2,9,2);l.position.set(x,y+.4,z);group.add(l);}
function battlements(x,z,w,d,h){for(let a=-w/2+.4;a<w/2;a+=1.7)box(x+a,h,z,.7,.75,d,stone);}
function arch(x,z,w,h,depth,group=surface){box(x-w/2,.0,z,1,h,depth,stone,group,true);box(x+w/2,.0,z,1,h,depth,stone,group,true);box(x,h-1,z,w,1,depth,stone,group);}
function building(x,z,w,d,h,m=brick){box(x,0,z,w,h,d,m,surface,true);const roofMesh=new T.Mesh(new T.ConeGeometry(w*.76,h*.55,4),roofMat);roofMesh.rotation.y=Math.PI/4;roofMesh.scale.z=d/w;roofMesh.position.set(x,h+h*.275,z);roofMesh.castShadow=true;surface.add(roofMesh);for(let a=-w/2+1.4;a<w/2;a+=2.4){box(x+a,1.9,z+d/2+.04,.65,1.1,.09,dark);box(x+a,2,z+d/2+.11,.45,.8,.08,mat('#d7b674',{emissive:'#795928',emissiveIntensity:.4}));}box(x,0,z+d/2+.08,1.2,2.2,.12,wood);}
function sign(text,x,y,z,group=surface){const c=document.createElement('canvas');c.width=512;c.height=96;const c2=c.getContext('2d');c2.fillStyle='#1e282ddd';c2.fillRect(0,0,512,96);c2.strokeStyle='#ba9d64';c2.strokeRect(4,4,504,88);c2.fillStyle='#f0ddb7';c2.font='32px Georgia';c2.textAlign='center';c2.fillText(text,256,59);const tex=new T.CanvasTexture(c),s=new T.Sprite(new T.SpriteMaterial({map:tex,transparent:true,depthWrite:false}));s.position.set(x,y,z);s.scale.set(5.7,1.07,1);group.add(s);return s;}
box(0,-.35,0,70,.35,70,earth);box(0,-.05,10,9,.08,50,pale);box(0,-.04,13,49,.09,6,pale);box(18,-.04,-3,6,.08,33,pale);box(-18,-.04,3,6,.08,23,pale);
// One outer wall encloses every surface space. No overworld beyond it.
for(const x of [-34,34]){box(x,0,0,1.8,8.5,68,stone,surface,true);for(let z=-32;z<=32;z+=2)box(x,8.5,z,1.8,.9,.9,stone);}
for(const z of [-34,34]){box(0,0,z,68,8.5,1.8,stone,surface,true);battlements(0,z,68,1.8,8.5);}
for(const x of [-32,32])for(const z of [-32,32]){cyl(x,0,z,3,12);cyl(x,12,z,3.2,.5);for(let a=0;a<8;a++){const t=a*Math.PI/4;box(x+Math.sin(t)*2.7,12.5,z+Math.cos(t)*2.7,.8,1,.8,stone);}}
// Keep: open, traversable hall with columns and visibly closed deeper doors.
box(0,0,-30,18,11,3,stone,surface,true);box(-9,0,-23,2,9,12,stone,surface,true);box(9,0,-23,2,9,12,stone,surface,true);box(0,-.01,-23,18,.12,13,brick);arch(0,-17,9,8,1.5);box(0,8,-23,19,1,14,stone);for(const x of [-6,6]){cyl(x,0,-23,.55,8);torch(x,-21,3);}box(0,0,-28,2,3,.25,wood);sign('THE KEEP',0,9.5,-16.8);
building(-24,23,9,8,5);building(-25,9,7,6,4);building(-10,23,7,7,4);building(25,24,11,8,5);building(27,8,7,10,5);building(27,-13,8,13,7);building(-25,-26,8,8,6);
sign('LOWTOWN',-17,4,18);sign('FORGE QUARTER',19,5,18);sign('GARRISON ROW',19,5,-2);
// Merchant-side crowd and street furnishing.
for(const [x,z]of [[-7,12],[7,12]]){box(x,0,z,3,1,2,wood,surface,true);box(x,2.6,z,3.6,.15,3,mat(x<0?'#727754':'#8c6659'));for(const dx of [-1.5,1.5])box(x+dx,0,z,.1,2.7,.1,wood);}
for(const [x,z]of [[-12,3],[-9,-7],[7,2],[15,-12],[-26,-12]]){box(x,0,z,2.1,1.7,1.6,wood,surface,true);box(x,1.65,z,2.15,.08,1.7,gold);}
for(const [x,z]of [[-14,8],[-14,11],[-13,-8],[10,18],[-27,17]]){cyl(x,0,z,.25,3,wood);const leaf=new T.Mesh(new T.IcosahedronGeometry(1.8,0),mat('#596b4b'));leaf.position.set(x,3.5,z);surface.add(leaf);}
for(const [x,z]of [[-14,-1],[-14,1],[-14,3],[-10,-10]])box(x,0,z,2.5,1.25,2,mat('#536047'));
for(const [x,z]of [[-18,14],[18,13],[19,-4],[-20,-7],[3,-15]])torch(x,z);
// Compromised inner wall provides one authored roof traversal shortcut.
box(-15,0,-6,1,2.8,12,stone,surface,true);box(-20,2.8,-10,11,.4,3,stone);for(let i=0;i<6;i++)box(-14.3,.3+i*.4,-2,.18,.08,.7,wood);
// Lowtown holding court, separate from the sealed Garrison tunnels.
box(-29,0,-1,1,3.5,10,stone,surface,true);box(-24,0,-6,10,3.5,1,stone,surface,true);box(-24,0,4,10,3.5,1,stone,surface,true);for(let x=-27;x<-20;x+=.6)box(x,0,2,.07,2.7,.1,dark);sign('Holding court',-24,4,4);
// Underneath geometry is directly below the Keep; entering has no load screen.
box(0,-12.35,-5,26,.35,26,dark,below);for(const x of [-13,13])box(x,-12,-5,1,10,26,dark,below,true);for(const z of [-18,8])box(0,-12,z,26,10,1,dark,below,true);
for(const x of [-8,8])for(const z of [-13,3])cyl(x,-12,z,1,9,stone,below);
box(0,-12,-12,5,1.4,3,stone,below,true);for(let i=0;i<5;i++){const ring=new T.Mesh(new T.TorusGeometry(3.1+i*.13,.05,5,40),mat('#4b8a8d',{emissive:'#306568',emissiveIntensity:.6}));ring.position.set(0,-8+i*.25,-15);ring.rotation.x=.17*i;below.add(ring);}
torch(-7,-5,-10,below);torch(7,-13,-10,below);const underLight=new T.PointLight('#6bbcc7',2.8,30,2);underLight.position.set(0,-6,-13);below.add(underLight);
function actor(color,group=surface){const a=new T.Group(),cloth=mat(color),skin=mat('#bba28b');const torso=box(0,.65,0,.6,.7,.38,cloth,a);const head=new T.Mesh(new T.IcosahedronGeometry(.24,1),skin);head.position.y=1.65;a.add(head);const hood=new T.Mesh(new T.SphereGeometry(.275,8,6),cloth);hood.position.set(0,1.72,-.065);hood.scale.set(1,1,1.05);a.add(hood);const arms=[box(-.39,.58,0,.17,.66,.19,cloth,a),box(.39,.58,0,.17,.66,.19,cloth,a)],legs=[box(-.18,0,0,.21,.7,.23,dark,a),box(.18,0,0,.21,.7,.23,dark,a)];group.add(a);a.userData={arms,legs,head,torso};return a;}
const player=actor('#354d51');scene.add(player);player.rotation.y=Math.PI;player.traverse(o=>{if(o.material)o.material=o.material.clone();});const cloak=new T.Mesh(new T.ConeGeometry(.45,1.0,6,1,true),mat('#314b52',{side:T.DoubleSide}));cloak.position.set(0,.85,-.16);player.add(cloak);
function npc(id,x,z,color){const mesh=actor(color);mesh.position.set(x,0,z);mesh.rotation.y=Math.PI;npcs.push({id,mesh,x,z});sign(id==='commander'?'Garrison Commander':id==='elder'?'Hollow Kin Elder':'Master Artisan',x,2.9,z);interactions.push({id:'npc_'+id,x,z,label:'Speak · '+(id==='commander'?'Garrison Commander':id==='elder'?'Hollow Kin Elder':'Master Artisan'),run:()=>openNPC(id)});}
npc('elder',-18,16,'#726952');npc('artisan',21,14,'#816248');npc('commander',18,0,'#5a6270');
for(let i=0;i<5;i++){const a=actor(['#727264','#8c715b','#5c7574'][i%3]);a.position.set(-4+(i%3)*1.3,0,12+Math.floor(i/3));a.rotation.y=i*1.6;}
function guard(id,path,construct=false){const mesh=actor(construct?'#576d73':'#8b6653',construct?below:surface);if(construct)mesh.scale.set(1.4,1.6,1.4);const coneGeo=new T.CircleGeometry(construct?8:7,28,-.53,1.06);coneGeo.rotateX(-Math.PI/2);coneGeo.rotateY(-Math.PI/2);const cone=new T.Mesh(coneGeo,new T.MeshBasicMaterial({color:0xe9c780,transparent:true,opacity:.11,depthWrite:false,side:T.DoubleSide}));(construct?below:surface).add(cone);const old=state.world.guards[id];guards.push({id,path,mesh,cone,x:path[0][0],z:path[0][1],to:1,heading:0,suspicion:0,status:old?.status||'patrol',health:old?.health??(construct?160:70),construct,attackAt:0,searchFor:0});}
guard('archive_guard',[[17,-8],[17,-21],[22,-21],[22,-8]]);guard('court_guard',[[-18,0],[-18,-8],[-16,-8],[-16,0]]);guard('reinforcement',[[6,-14],[13,-14],[13,-5],[6,-5]]);guard('guardian',[[-7,-7],[6,-7],[6,0],[-7,0]],true);
function interactable(id,x,z,label,run,under=false){interactions.push({id,x,z,label,run,under});}
const orders=box(21.3,.7,-20,.8,.12,.6,pale);interactable('orders',21.3,-20,'Recover patrol orders',()=>{if(state.world.collected.orders)return toast('The archive shelf is empty.');state.world.collected.orders=true;perform('take_orders');orders.visible=false;});
const fragment=new T.Mesh(new T.OctahedronGeometry(.38),mat('#77c1c1',{emissive:'#408889',emissiveIntensity:1}));fragment.position.set(0,-10.1,-12);below.add(fragment);interactable('fragment',0,-10,'Recover Emberworks fragment',()=>{const r=perform('take_fragment');if(r?.ok)state.world.collected.fragment=true;},true);
const artifact=new T.Mesh(new T.TorusKnotGeometry(.24,.07,48,8),gold);artifact.position.set(-9,-10.7,-14);below.add(artifact);interactable('veil',-9,-14,'Recover Hushmarch device',()=>{perform('find_ability',{id:'veil_step'});state.world.collected.veil=true;},true);
interactable('cell',-22,1,'Open holding court',()=>{if(state.quest.protection==='not_started')return toast('Speak with the Hollow Kin Elder first.');if(alarm>0)return toast('Lose the searching guards before opening the court.');const discreet=guards.filter(g=>!g.construct).every(g=>g.status!=='defeated')&&!state.world.exposed;perform(discreet?'release_quiet':'release_negotiated');});
interactable('roster',-26,-3,'Remove identifying names',()=>{if(state.quest.protection==='not_started'||state.quest.protection==='in_progress')return toast('Get the detained Kin out first.');perform('improve_protection');state.world.collected.roster=true;});
interactable('climb',-13.7,-2,'Climb damaged wall',()=>startClimb(true));
interactable('descendRoof',-18,-10,'Descend damaged wall',()=>startClimb(false),false);
interactable('cellar',-25,-11,'Inspect deliberate tool marks',()=>{if(!state.world.visited.underneath){perform('discover_entrance',{id:'lowtown_cellar'});state.world.visited.underneath=true;toast('The marks lead behind a false wall. A stair descends below the Keep.');}underground=true;roof=false;pos.x=0;pos.z=5;save();});
interactable('surface',0,6,'Climb to the surface',()=>{underground=false;pos.x=-24;pos.z=-11;save();},true);
interactable('rest',0,23,'Rest at the bailey fountain',()=>{if(alarm>0)return toast('You cannot rest while guards are searching.');perform('rest');heat=0;});
interactable('sealed',24,-28,'Inspect sealed tunnel',()=>toast('Military seals layered over older stone. No way through.'));
box(24,0,-28,2.5,3.5,.4,dark);cyl(0,0,25,1.9,.6,stone);cyl(0,.6,25,1.7,.1,mat('#5a929b',{metalness:.35,roughness:.15}));
function panel(title,kicker,html){focusReturn=document.activeElement;paused=true;clearInput();$('shade').hidden=false;$('panelTitle').textContent=title;$('panelKicker').textContent=kicker;$('panelBody').innerHTML=html;$('closePanel').focus();}
function closePanel(){paused=false;activeNPC=null;dialogue=null;$('shade').hidden=true;$('scene').focus();save();}
$('closePanel').onclick=closePanel;
function btn(text,handler,parent=$('panelBody'),className=''){const b=document.createElement('button');b.textContent=text;b.className=className;b.onclick=handler;parent.append(b);return b;}
function openNPC(id){activeNPC=id;const name=id==='commander'?'Garrison Commander':id==='elder'?'Hollow Kin Elder':'Master Artisan';panel(name,id==='elder'?'LOWTOWN':id==='artisan'?'FORGE QUARTER':'GARRISON ROW','<p class="sub">Choose a topic. You can return as circumstances change.</p><div class="choices" id="topics"></div>');activeNPC=id;const topics=getTopics(state,id);
if(topics[0]?.disposition)$('topics').insertAdjacentHTML('beforeend','<p class="sub">You read their manner as '+esc(topics[0].disposition)+'.</p>');
for(const t of topics){const b=btn(t.title+(t.isNew?'  ·':''),()=>speak(t.id),$('topics'));b.disabled=!t.available;
  if(t.gateHint){const hints={reputation:'Greater local trust may open this further.',quest:'The outcome of a task may open this further.',exchange:'Deliver the evidence they need.',composite:'More than one condition remains.'};$('topics').insertAdjacentHTML('beforeend','<p class="gateHint">'+esc(hints[t.gateHint]||'There is more to learn here.')+'</p>');}
}const actions=document.createElement('div');actions.className='spaced';$('panelBody').append(actions);
if(id==='elder'&&state.quest.protection==='not_started')btn('Ask who needs protection',()=>{perform('start_protection');openNPC(id);},actions);
if(id==='artisan'&&state.inventory.includes('fragment'))btn('Deliver the fragment',()=>{perform('deliver_fragment');openNPC(id);},actions);
if(id==='commander'&&state.world.collected.orders&&!state.world.collected.ordersDelivered)btn('Return the patrol orders',()=>{const r=perform('garrison_aid');if(r?.ok)state.world.collected.ordersDelivered=true;openNPC(id);},actions);
btn('Leave conversation',closePanel,actions);}
function speak(topicId){dialogue=chooseTopic(state,activeNPC,topicId);renderDialogue();save();}
function renderDialogue(){const d=dialogue;if(!d)return;const id=activeNPC;$('panelBody').innerHTML='<p class="quote">'+esc(d.text)+'</p><div class="choices" id="responses"></div>';for(const r of d.responses||[])btn(r.text,()=>{dialogue=chooseResponse(state,id,r.id);if(!dialogue||dialogue.ended||dialogue.returnToTopics)openNPC(id);else renderDialogue();save();},$('responses'));btn('Other topics',()=>openNPC(id),$('responses'));btn('Leave conversation',closePanel,$('responses'));}
function journal(){const entries=getJournal(state);panel('Your journal','CASTLE REALM',Array.isArray(entries)?entries.map(q=>'<h2>'+esc(q.title)+'</h2><span class="pill">'+esc(q.status)+'</span>'+q.objectives.map(o=>'<p>'+esc(typeof o==='string'?o:o.text||o.title)+'</p>').join('')).join(''):'<p>'+esc(entries)+'</p>');}
function pack(){panel('Pack & equipment','YOUR BELONGINGS','<p class="sub">Ancient devices are found through discovery, independently of attributes.</p>');for(const id of state.inventory){const item=ITEMS[id]||{name:id,description:''};const row=document.createElement('div');row.className='row';row.innerHTML='<div><strong>'+esc(item.name)+'</strong><p>'+esc(item.description||item.desc||'')+'</p></div>';$('panelBody').append(row);if(item.type==='consumable')btn('Use',()=>{perform('use_item',{id});pack();},row);if(['weapon','armor'].includes(item.type))btn('Equip',()=>{perform('equip_item',{id});pack();},row);}const c=state.crowns??state.player.crowns??0,g=state.materials?.gems??0;$('panelBody').insertAdjacentHTML('beforeend','<p class="pill">'+esc(c)+' Crowns · '+esc(g)+' rare jewels</p>');if(state.abilities?.includes('veil_step'))$('panelBody').insertAdjacentHTML('beforeend','<h2>Veil Step · Hushmarch</h2><p>R / Veil: brief concealment and noise dampening. Overuse raises malfunction risk and wakes nearby constructs. Cool down between uses.</p>');}
function skills(){const p=state.player;panel('Character','LEVEL '+p.level+' · '+p.xp+' XP','<p class="note">'+p.attributePoints+' attribute points available. Allocations are permanent. Skills grow through varied practice.</p><div class="columns" id="trees"></div>');for(const tree of ['might','finesse','wit']){const section=document.createElement('section');section.innerHTML='<h2>'+tree[0].toUpperCase()+tree.slice(1)+' · '+p.attributes[tree]+'</h2><p class="sub">Practice: '+Number(p.pp[tree]||0).toFixed(1)+'</p>';$('trees').append(section);if(p.attributePoints>0)btn('Allocate +1 permanently',()=>{const r=allocateAttribute(state,tree);toast(r?.message);save();skills();},section);(SKILLS[tree]||[]).forEach((s,i)=>{const learned=Array.isArray(p.skills[tree])?p.skills[tree].includes(s.id)||p.skills[tree].includes(s.name):Number(p.skills[tree])>i;section.insertAdjacentHTML('beforeend','<div class="skill '+(learned?'earned':'')+'"><strong>'+(learned?'✓ ':'')+esc(s.name||s.title||s)+'</strong>'+esc(s.description||s.desc||'')+'</div>');});}}
function menu(){panel('Castle Realm','A QUIET PASSAGE · v0.2','<p>A contained encounter built from your two design documents. Encounter layout, dialogue lines, and numeric balance are provisional.</p><div class="spaced" id="menuActions"></div><h2>Travel between discovered gates</h2><div class="spaced" id="travel"></div><h2>Controls</h2><p class="sub">WASD: move. Drag the scene or Q/E: turn camera. C: crouch. F: interact. X: non-lethal takedown from behind. V: lethal takedown. Space: risky direct strike. R: found Veil Step. J / I / K: journal / pack / character. Escape: close panel. Touch: left stick to move, drag the view to turn, right buttons to act.</p>');btn('Resume',closePanel,$('menuActions'),'primary');if(typeof location!=='undefined'&&location.protocol!=='file:'){for(const [label,path]of [['Download game','castle-realm-slice.html'],['Source & design documents','castle-realm-source.zip']]){const a=document.createElement('a');a.textContent=label;a.href=path;a.download='';a.className='download';$('menuActions').append(a);}}btn('Save progress',()=>save(true),$('menuActions'));btn('Export save',()=>{const a=document.createElement('a');save();a.href=URL.createObjectURL(new Blob([serialize(state)],{type:'application/json'}));a.download='castle-realm-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);},$('menuActions'));const input=document.createElement('input');input.type='file';input.accept='.json';input.hidden=true;input.onchange=async()=>{try{const candidate=deserialize(await input.files[0].text());const cp=candidate.world?.playerPosition;if(cp&&(!Number.isFinite(cp.x)||!Number.isFinite(cp.z)||Math.abs(cp.x)>33||Math.abs(cp.z)>33))throw new Error('Invalid player position');state=candidate;worldState();restoreWorld();save();closePanel();toast('Save restored.');}catch{toast('That save could not be read. Your progress was kept.');}};$('menuActions').append(input);btn('Import save',()=>input.click(),$('menuActions'));btn('New journey',()=>{panel('Start a new journey?','CURRENT SAVE','<p>This replaces the current device save. Export it first if you want to keep it.</p><div class="spaced" id="newActions"></div>');btn('Keep current journey',menu,$('newActions'));btn('Start new journey',()=>{state=createState();worldState();restoreWorld();save();closePanel();},$('newActions'));},$('menuActions'));for(const g of gates){if(state.world.visited[g.id]){const b=btn(g.name,()=>{if(alarm>0)return toast('Lose your pursuers before travelling.');pendingClimb=null;pendingTakedown=null;underground=false;roof=false;pos.x=g.x;pos.z=g.z;closePanel();},$('travel'));b.disabled=alarm>0;}}}
function restoreWorld(){
  const w=worldState();Object.assign(pos,w.playerPosition);underground=!!w.underneath;
  roof=!underground&&!!w.roof&&pos.x>=-26&&pos.x<=-14&&pos.z>=-12&&pos.z<=-8;
  crouched=!!w.crouched;yaw=w.yaw??0;pitch=w.pitch??.24;alarm=w.alarm??0;heat=w.heat??0;
  veilUntil=clock+(w.veilRemaining??0);attackCooldown=clock+(w.attackRemaining??0);
  pendingTakedown=null;pendingClimb=null;coverGraceUntil=0;coverTime=0;wasInCover=false;nearest=null;clearInput();
  $('crouchBtn').textContent=crouched?'Stand':'Crouch';
  for(const g of guards){const old=w.guards[g.id]||{};g.status=old.status||'patrol';g.health=old.health??(g.construct?160:70);g.x=old.x??g.path[0][0];g.z=old.z??g.path[0][1];g.to=(old.to??1)%g.path.length;g.heading=old.heading??0;g.suspicion=old.suspicion??0;g.alerted=old.alerted??g.suspicion>=1;g.graceUsed=!!old.graceUsed;g.graceRemaining=old.graceRemaining??0;g.lastX=old.lastX??g.x;g.lastZ=old.lastZ??g.z;g.attackAt=clock+(old.attackRemaining??0);g.mesh.rotation.z=0;g.mesh.position.set(g.x,g.construct?-12:0,g.z);}
}
function startClimb(up){
  if(paused||pendingClimb||pendingTakedown||underground||up===roof)return;
  const route=[{x:pos.x,z:pos.z,y:roof?3.2:0},...(up?[{x:-13.7,z:-2,y:3.2},{x:-15,z:-2,y:3.2},{x:-15,z:-10,y:3.2},{x:-18,z:-10,y:3.2}]:[{x:-15,z:-10,y:3.2},{x:-15,z:-2,y:3.2},{x:-13.7,z:-2,y:3.2},{x:-13,z:-2,y:0}])];
  pendingClimb={from:{...pos},fromRoof:roof,toRoof:up,route,y:roof?3.2:0,elapsed:0,duration:(up?4.6:4.2)/getEffects(state).climbSpeedMultiplier};
  clearInput();toast(up?'Climbing the damaged wall…':'Descending to the street…');
}
function updateClimb(dt){
  if(!pendingClimb)return;
  const c=pendingClimb;c.elapsed=Math.min(c.duration,c.elapsed+dt);const f=c.elapsed/c.duration;
  const stops=c.toRoof?[0,.3,.4,.85,1]:[0,.15,.6,.7,1];
  let segment=0;while(segment<3&&f>stops[segment+1])segment++;
  const local=(f-stops[segment])/(stops[segment+1]-stops[segment]),a=c.route[segment],b=c.route[segment+1];
  pos.x=a.x+(b.x-a.x)*local;pos.z=a.z+(b.z-a.z)*local;c.y=a.y+(b.y-a.y)*local;
  if(f>=1){roof=c.toRoof;pendingClimb=null;if(roof)perform('climb',{id:'lowtown_wall'});else save();}
}
function traversalHeight(){
  if(!pendingClimb)return underground?-12:roof?3.2:0;
  return pendingClimb.y;
}
$('journalBtn').onclick=journal;$('packBtn').onclick=pack;$('skillsBtn').onclick=skills;$('menuBtn').onclick=menu;
function blocked(x,z){if(underground){if(x<-12||x>12||z<-17||z>7)return true;}else if(Math.abs(x)>32.5||Math.abs(z)>32.5)return true;if(roof)return false;return colliders.some(c=>c.below===underground&&Math.abs(x-c.x)<c.w/2+.34&&Math.abs(z-c.z)<c.d/2+.34);}
function lineBlocked(ax,az,bx,bz){const length=Math.hypot(bx-ax,bz-az),steps=Math.ceil(length*3);for(let i=1;i<steps;i++){const f=i/steps,x=ax+(bx-ax)*f,z=az+(bz-az)*f;if(colliders.some(c=>c.below===underground&&Math.abs(x-c.x)<c.w/2&&Math.abs(z-c.z)<c.d/2))return true;}return false;}
function move(dx,dz){if(!blocked(pos.x+dx,pos.z))pos.x+=dx;if(!blocked(pos.x,pos.z+dz))pos.z+=dz;if(roof&&(pos.x< -26||pos.x> -14||pos.z< -12||pos.z> -8)){roof=false;pos.x=-13;pos.z=-2;}}
function nearestGuard(){return guards.filter(g=>g.construct===underground&&g.status!=='unconscious'&&g.status!=='defeated'&&(g.id!=='reinforcement'||alarm>0)).sort((a,b)=>Math.hypot(a.x-pos.x,a.z-pos.z)-Math.hypot(b.x-pos.x,b.z-pos.z))[0];}
function takedown(lethal=false){if(paused||pendingTakedown||pendingClimb)return;const g=nearestGuard();if(!g||Math.hypot(g.x-pos.x,g.z-pos.z)>1.8||lineBlocked(pos.x,pos.z,g.x,g.z))return toast('Get close behind a patrol.');const behind=(pos.x-g.x)*Math.sin(g.heading)+(pos.z-g.z)*Math.cos(g.heading)<-.2;if(g.construct)return toast('This construct cannot be subdued. Avoid it.');if(!behind||g.suspicion>.65||!crouched)return toast('Crouch behind an unaware guard for a takedown.');pendingTakedown={guard:g,lethal,until:clock+getEffects(state).takedownSeconds};toast(lethal?'Closing for a lethal strike…':'Subduing the guard…');}
function finishTakedown(){const p=pendingTakedown;if(!p)return;const g=p.guard;if(g.suspicion>.85||Math.hypot(g.x-pos.x,g.z-pos.z)>3){pendingTakedown=null;return toast('The opening is gone. Reposition.');}g.status=p.lethal?'defeated':'unconscious';g.health=0;perform(p.lethal?'lethal_takedown':'takedown',{id:g.id});if(p.lethal){state.world.exposed=true;alarm=18;}pendingTakedown=null;save();}
function strike(){if(paused||pendingClimb||pendingTakedown||clock<attackCooldown)return;attackCooldown=clock+.7;if(state.player.stamina<20)return toast('Too exhausted to strike.');state.player.stamina-=20;const g=nearestGuard();alarm=24;state.world.exposed=true;if(!g||Math.hypot(g.x-pos.x,g.z-pos.z)>2.2||lineBlocked(pos.x,pos.z,g.x,g.z))return toast('The noise carries. Guards are searching.');const skills=state.player.skills.might;const bonus=(Array.isArray(skills)?skills.length:Number(skills))>=6?8:0;g.health-=18+state.player.attributes.might*3+bonus;g.suspicion=1;g.alerted=true;g.lastX=pos.x;g.lastZ=pos.z;g.mesh.rotation.z=.16;if(g.health<=0){g.status='defeated';perform('win_combat',{id:g.id});}else toast(g.construct?'The construct barely falters. Break line of sight.':'The alarm is raised. More guards are coming.');save();}
function veil(){if(paused||pendingClimb||pendingTakedown)return;if(!state.abilities?.includes('veil_step'))return toast('No Hushmarch device equipped.');if(clock<veilUntil)return;if(state.player.stamina<25)return toast('Recover your breath before using the device.');state.player.stamina-=25;const skillReduction=getEffects(state).malfunctionReduction;const malfunction=Math.random()<Math.max(0,heat/160-.03*state.player.attributes.wit-skillReduction);heat=Math.min(100,heat+35);if(malfunction){alarm=18;veilUntil=0;toast('The device cracks with static. Something heard it.');}else{veilUntil=clock+6;perform('ancient_tech_use',{id:'veil_step',malfunction:false});toast('Veil Step. Move quietly.');}}
function interact(){if(paused||pendingClimb||pendingTakedown)return;if(nearest){nearest.run();save();}else toast('Move closer to someone or something you can inspect.');}
function toggleCrouch(){if(paused||pendingClimb||pendingTakedown)return;crouched=!crouched;$('crouchBtn').textContent=crouched?'Stand':'Crouch';}
$('interactBtn').onclick=interact;$('crouchBtn').onclick=toggleCrouch;$('takeBtn').onclick=()=>takedown();$('lethalBtn').onclick=()=>takedown(true);$('strikeBtn').onclick=strike;$('techBtn').onclick=veil;
function clearInput(){for(const k of Object.keys(keys))keys[k]=false;stick.x=stick.y=0;$('knob').style.transform='';}
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(paused)closePanel();else menu();return;}if(paused)return;keys[e.code]=true;if(e.repeat)return;({KeyC:toggleCrouch,KeyF:interact,KeyX:()=>takedown(),KeyV:()=>takedown(true),Space:strike,KeyR:veil,KeyJ:journal,KeyI:pack,KeyK:skills})[e.code]?.();});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{clearInput();if(!paused)menu();});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInput();if(!paused)menu();save();}});
let drag=null;$('scene').addEventListener('pointerdown',e=>{if(paused)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};$('scene').setPointerCapture(e.pointerId);});$('scene').addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId)return;yaw-=(e.clientX-drag.x)*.006;pitch=Math.max(-.15,Math.min(.75,pitch+(e.clientY-drag.y)*.004));drag.x=e.clientX;drag.y=e.clientY;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('scene').addEventListener(ev,()=>drag=null);
let stickPointer=null;function stickMove(e){if(e.pointerId!==stickPointer)return;const r=$('stick').getBoundingClientRect();let x=(e.clientX-r.left-r.width/2)/40,y=(e.clientY-r.top-r.height/2)/40;const l=Math.max(1,Math.hypot(x,y));stick.x=x/l;stick.y=y/l;$('knob').style.transform=`translate(${stick.x*32}px,${stick.y*32}px)`;}
$('stick').onpointerdown=e=>{e.preventDefault();stickPointer=e.pointerId;$('stick').setPointerCapture(e.pointerId);stickMove(e);};$('stick').onpointermove=stickMove;for(const ev of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(ev,()=>{stickPointer=null;stick.x=stick.y=0;$('knob').style.transform='';});
function guardActive(g){return g.construct===underground&&(g.id!=='reinforcement'||alarm>0)&&!['unconscious','defeated'].includes(g.status);}
function updateCover(dt,crowd,foliage,moving,effects){
  const behindCover=guards.some(g=>guardActive(g)&&Math.hypot(g.x-pos.x,g.z-pos.z)<11&&lineBlocked(g.x,g.z,pos.x,pos.z));
  const inCover=crowd||foliage||behindCover;
  if(inCover)coverTime+=dt;
  else {if(wasInCover&&coverTime>=.4&&moving)coverGraceUntil=clock+effects.coverGraceSeconds;coverTime=0;}
  wasInCover=inCover;
}
function updateGuards(dt,moving,running,crowd=false,foliage=false){
  const effects=getEffects(state),veiled=clock<veilUntil,shadow=clock<coverGraceUntil;
  for(const g of guards){
    const applicable=g.construct===underground&&(g.id!=='reinforcement'||alarm>0);
    g.mesh.visible=applicable;g.cone.visible=applicable;if(!applicable)continue;
    if(['unconscious','defeated'].includes(g.status)){g.mesh.position.set(g.x,(g.construct?-12:0)+.25,g.z);g.mesh.rotation.z=Math.PI/2;g.cone.visible=false;continue;}
    g.mesh.rotation.z*=.85;
    const d=Math.hypot(pos.x-g.x,pos.z-g.z),dot=((pos.x-g.x)*Math.sin(g.heading)+(pos.z-g.z)*Math.cos(g.heading))/Math.max(d,.1);
    const restricted=underground||pos.z< -4||(pos.x< -16&&pos.z<6);
    const clearSight=!lineBlocked(g.x,g.z,pos.x,pos.z)&&!roof;
    const sight=d<(g.construct?8:7)&&(dot>.82||d<1.1)&&clearSight&&(!foliage||d<1.1);
    const sound=moving&&d<(running?5:1.7*effects.walkingNoiseMultiplier)&&(!crouched||d<.7)&&!roof;
    const noticed=(restricted||alarm>0)&&(sight||sound)&&!veiled;
    const lit=lightSources.some(l=>l.under===underground&&Math.hypot(pos.x-l.x,pos.z-l.z)<4.5);
    const visual=sight?(crouched?.32:.85)*(lit?1.2:.65)*(crowd&&!running?effects.crowdDetectionMultiplier:1)*(shadow?.45:1):0;
    const audible=sound?(running?1.1:.3):0;
    g.graceRemaining=Math.max(0,(g.graceRemaining||0)-dt);
    g.suspicion=Math.max(0,Math.min(1,g.suspicion+(noticed?dt*Math.max(visual,audible):-dt*.3)));
    if(noticed){g.lastX=pos.x;g.lastZ=pos.z;}
    if(g.suspicion>=1&&!g.alerted){
      if(effects.alertGraceSeconds&&!g.graceUsed){g.graceUsed=true;g.graceRemaining=effects.alertGraceSeconds;}
      if(g.graceRemaining>0)g.suspicion=.99;
      else {g.alerted=true;state.world.exposed=true;}
    }
    if(g.alerted&&noticed)alarm=24;
    if(g.suspicion===0){g.alerted=false;if(alarm<=0){g.graceUsed=false;g.graceRemaining=0;}}
    let tx,tz;
    if(g.alerted&&g.suspicion>0){tx=g.lastX??g.x;tz=g.lastZ??g.z;}
    else {[tx,tz]=g.path[g.to];if(Math.hypot(tx-g.x,tz-g.z)<.35){g.to=(g.to+1)%g.path.length;[tx,tz]=g.path[g.to];}}
    const distance=Math.hypot(tx-g.x,tz-g.z),speed=g.alerted?(g.construct?2.7:3.4):1.1;
    if(distance>.08){g.heading=Math.atan2(tx-g.x,tz-g.z);const step=Math.min(Math.max(0,distance-(g.alerted?.95:0)),speed*dt),dx=Math.sin(g.heading)*step,dz=Math.cos(g.heading)*step;
      const hit=(x,z)=>colliders.some(c=>c.below===underground&&Math.abs(x-c.x)<c.w/2+.2&&Math.abs(z-c.z)<c.d/2+.2);
      if(!hit(g.x+dx,g.z))g.x+=dx;if(!hit(g.x,g.z+dz))g.z+=dz;
    }
    g.mesh.position.set(g.x,g.construct?-12:0,g.z);g.mesh.rotation.y=g.heading;
    g.cone.visible=d<effects.awarenessDistance;g.cone.position.set(g.x,(g.construct?-12:0)+.05,g.z);g.cone.rotation.y=g.heading;g.cone.material.color.set(g.alerted?'#de6656':'#d9c180');g.cone.material.opacity=.07+g.suspicion*.13;
    if(d<1.8&&g.alerted&&noticed&&clearSight&&clock>g.attackAt){g.attackAt=clock+1.2;state.player.health-=g.construct?42:15;toast(g.construct?'A crushing impact. Escape the chamber.':'You have been struck. Break line of sight.');}
  }
}
function mapDraw(){const c=$('map').getContext('2d');c.clearRect(0,0,160,160);c.strokeStyle='#baa77d';c.lineWidth=1;c.strokeRect(14,14,132,132);c.fillStyle='#62716c';if(!underground){for(const g of gates){if(state.world.visited[g.id]){c.fillRect(80+g.x*1.8-3,80+g.z*1.8-3,6,6);}}c.fillStyle='#aa9b7d';c.fillRect(65,25,30,20);}else{c.strokeStyle='#59999a';c.strokeRect(52,45,56,58);}c.save();c.translate(80+pos.x*1.8,80+pos.z*1.8);c.rotate(-yaw);c.fillStyle='#f7ddb0';c.beginPath();c.moveTo(0,-5);c.lineTo(3,4);c.lineTo(-3,4);c.closePath();c.fill();c.restore();c.fillStyle='#c7c8b9';c.font='10px sans-serif';c.fillText('N',77,10);}
function tick(t){requestAnimationFrame(tick);const dt=Math.min(.04,(t-last)/1000||0);last=t;uiClock+=dt;if(!paused)clock+=dt;surface.visible=!underground;below.visible=underground;scene.background.set(underground?'#111e29':'#64717e');scene.fog.color.copy(scene.background);scene.fog.near=underground?8:36;scene.fog.far=underground?32:100;sun.intensity=underground?.15:1.9;
if(!paused){yaw+=((keys.KeyQ?1:0)-(keys.KeyE?1:0))*dt*1.8;let x=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+stick.x,z=(keys.KeyS||keys.ArrowDown?1:0)-(keys.KeyW||keys.ArrowUp?1:0)+stick.y;if(pendingTakedown||pendingClimb){x=0;z=0;}const l=Math.max(1,Math.hypot(x,z));x/=l;z/=l;const moving=Math.hypot(x,z)>.05,running=!!keys.ShiftLeft&&!crouched&&state.player.stamina>1;const speed=crouched?1.6+state.player.attributes.finesse*.06:running?5.8:3.5;if(pendingClimb)updateClimb(dt);else move((x*Math.cos(yaw)+z*Math.sin(yaw))*speed*dt,(-x*Math.sin(yaw)+z*Math.cos(yaw))*speed*dt);if(moving)player.rotation.y=Math.atan2(x*Math.cos(yaw)+z*Math.sin(yaw),-x*Math.sin(yaw)+z*Math.cos(yaw));player.scale.y=crouched?.72:1;const walk=moving?Math.sin(clock*(running?13:8))*.35:0;player.userData.legs[0].rotation.x=walk;player.userData.legs[1].rotation.x=-walk;player.userData.arms[0].rotation.x=-walk;player.userData.arms[1].rotation.x=walk;
state.player.stamina=Math.max(0,Math.min(100,state.player.stamina+dt*(running&&moving?-11:10)));heat=Math.max(0,heat-dt*3);alarm=Math.max(0,alarm-dt);const crowd=!underground&&Math.hypot(pos.x+2,pos.z-12)<3,foliage=!underground&&crouched&&Math.abs(pos.x+14)<2&&pos.z>-1&&pos.z<5;const hidden=foliage;updateCover(dt,crowd,foliage,moving,getEffects(state));updateGuards(dt,moving||!!pendingClimb,running,crowd,foliage);if(pendingTakedown&&clock>=pendingTakedown.until)finishTakedown();if(crowd&&moving&&!state.world.collected.blend){perform('crowd_blend',{id:'bailey_crowd'});state.world.collected.blend=true;}
if(state.player.health<=0){state.player.health=100;state.player.stamina=100;alarm=0;underground=false;roof=false;pendingClimb=null;pendingTakedown=null;veilUntil=0;coverGraceUntil=0;pos.x=0;pos.z=22;for(const g of guards){g.suspicion=0;g.alerted=false;g.graceRemaining=0;g.graceUsed=false;}toast('You escaped wounded. Recover at the bailey and choose another approach.');save();}
for(const g of gates)if(!underground&&Math.hypot(pos.x-g.x,pos.z-g.z)<5&&!state.world.visited[g.id]){state.world.visited[g.id]=true;toast(g.name+' gate discovered.');save();}
nearest=interactions.filter(i=>!!i.under===underground&&!(i.id==='descendRoof'&&!roof)&&!(i.id==='orders'&&state.world.collected.orders)&&!(i.id==='fragment'&&state.world.collected.fragment)&&!(i.id==='veil'&&state.world.collected.veil)).filter(i=>Math.hypot(i.x-pos.x,i.z-pos.z)<2.6).sort((a,b)=>Math.hypot(a.x-pos.x,a.z-pos.z)-Math.hypot(b.x-pos.x,b.z-pos.z))[0];const clue=!nearest&&getEffects(state).clueDistance>2.6?interactions.find(i=>!!i.under===underground&&['cellar','sealed','roster','fragment','veil'].includes(i.id)&&!state.world.collected[i.id]&&Math.hypot(i.x-pos.x,i.z-pos.z)<getEffects(state).clueDistance&&!lineBlocked(pos.x,pos.z,i.x,i.z)):null;
$('prompt').textContent=pendingClimb?'Traversing the wall…':pendingTakedown?'Finishing takedown…':nearest?'F · '+nearest.label:clue?'You notice something nearby · move closer to inspect':'';
const suspicion=Math.max(0,...guards.filter(guardActive).map(g=>g.suspicion));$('status').textContent=clock<veilUntil?'Veiled':alarm>0?'Guards searching':suspicion>.85?'Almost spotted · find cover':suspicion>.25?'Suspicion rising':hidden?'Hidden in foliage':crowd?'Blending with the crowd':crouched?'Quiet movement':'Unnoticed';$('status').style.color=alarm>0?'#ef9a83':hidden?'#abd3a8':'#ddd6c5';saveClock+=dt;if(saveClock>8){save();saveClock=0;}}
player.position.set(pos.x,traversalHeight(),pos.z);player.traverse(o=>{if(o.material){o.material.transparent=clock<veilUntil;o.material.opacity=clock<veilUntil?.35:1;}});
const target=new T.Vector3(pos.x,player.position.y+1.45,pos.z);const desired=new T.Vector3(pos.x+Math.sin(yaw)*4.6+Math.cos(yaw)*.62,target.y+1+pitch*3,pos.z+Math.cos(yaw)*4.6-Math.sin(yaw)*.62);if(!roof){for(let i=1;i<=20;i++){const f=i/20,cx=target.x+(desired.x-target.x)*f,cz=target.z+(desired.z-target.z)*f;if(colliders.some(c=>c.below===underground&&Math.abs(cx-c.x)<c.w/2+.1&&Math.abs(cz-c.z)<c.d/2+.1)){desired.lerpVectors(target,desired,Math.max(.15,(i-1)/20));break;}}}camera.position.lerp(desired,.13);camera.lookAt(target.x-Math.sin(yaw)*2,target.y-.05,target.z-Math.cos(yaw)*2);
$('place').textContent=underground?'The Underneath':roof?'Lowtown · wall walk':pos.z<-15&&Math.abs(pos.x)<10?'The Keep':pos.x<-13?'Lowtown':pos.x>13?(pos.z<3?'Garrison Row':'Forge Quarter'):'Inner Bailey';$('hp').value=state.player.health;$('hpText').textContent=Math.ceil(state.player.health);$('stamina').value=state.player.stamina;$('abilityState').textContent=state.abilities?.includes('veil_step')?(heat>55?'Device unstable · let it cool':'Veil Step ready · R'):'';
orders.visible=!underground&&!state.world.collected.orders;fragment.visible=underground&&!state.world.collected.fragment;artifact.visible=underground&&!state.world.collected.veil;fragment.rotation.y=clock*.8;artifact.rotation.y=clock*.6;
const q=state.quest;$('objective').textContent=q.protection==='not_started'?'Find the Hollow Kin Elder in Lowtown.':q.protection==='in_progress'?'Protect the detained Hollow Kin in the holding court.':!q.proofDelivered?'Return to the Elder. Explore the optional hidden layer.':'Revisit the three knowing figures. Their answers have changed.';if(uiClock>toastUntil)$('toast').classList.remove('show');mapDraw();renderer.render(scene,camera);}
function resize(){renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();requestAnimationFrame(tick);
restoreWorld();
panel('A Quiet Passage','CASTLE REALM','<p class="quote">A sealed order. A frightened people. Machinery beneath old stone.</p><p>Speak to the Hollow Kin Elder in Lowtown. Protect the detained Kin, earn the Commander’s confidence, and discover what the Artisan can read in an ancient fragment.</p><p class="sub">One character. One enclosed domain. Stealth first. The Underneath is optional. This is a provisional encounter, not the unresolved main story.</p><p class="sub">WASD / left stick to move · drag the view to turn · C to crouch · F to interact. The journal keeps your objectives.</p><div class="spaced" id="startActions"></div>');btn('Enter the realm',closePanel,$('startActions'),'primary');btn('Controls & save options',menu,$('startActions'));
// Optional page tools expose the same journal/panels as the visible interface.
// They never return hidden reputation values or undiscovered world information.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'read_castle_journal',description:'Read the current visible quest journal.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(input&&Object.keys(input).length)throw new Error('No arguments accepted.');return {quests:getJournal(state)};}});register({name:'open_castle_panel',description:'Open the journal, inventory, character, or menu panel; pauses play.',inputSchema:{type:'object',properties:{panel:{type:'string',enum:['journal','pack','character','menu']}},required:['panel'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||Object.keys(input).length!==1||!['journal','pack','character','menu'].includes(input.panel))throw new Error('Choose one supported panel.');({journal,pack,character:skills,menu})[input.panel]();return {opened:input.panel};}});}
